### ISSUE TITLE
Initial note timing

### ISSUE THREAD

**Issue by sklink** [amiika/ziffers#58]
I've just set up Ziffers and am having an issue with the timing of the first few notes. Here's an exmaple:

```
require "~/ziffers/ziffers.rb"

live_loop :first do
  zplay "0 035"
end
```

Here's the log output from the first note:

```
{run: 27, time: 1.0, thread: :live_loop_first}
 └─ synth :beep, {note: 60.0, release: 1.0}
 
{run: 27, time: 1.5, thread: :live_loop_first}
 └─ synth :beep, {note: [60.0, 65.0, 69.0], release: 1.0}
 
{run: 27, time: 2.5, thread: :live_loop_first}
 └─ synth :beep, {note: 60.0, release: 1.0}
 
{run: 27, time: 3.5, thread: :live_loop_first}
 └─ synth :beep, {note: [60.0, 65.0, 69.0], release: 1.0}
```

You can see that the first note comes in at `1.0` and the chord then plays at `1.5`. After that, the timings are `1.0` apart.

I have tried this alongside a simple `play`, which does keep the correct timing.

I use my Mac for software dev so I don't think it would have trouble with the calculations under the hood, but that is a possibility.

Let me know if I can provide any more info. Thanks!

**Comment by amiika** [comment]
First of all, thanks for testing and posting issue! :)

It seems something has changed in Sonic Pi:

```
```

**Comment by amiika** [comment]
Changed default sched_ahead to 0.5 which fixes this for now ... until I figure out what is actually going on.
