### ISSUE TITLE
Treetop removed in recent commit

### ISSUE THREAD

**Issue by b08x** [amiika/ziffers#78]
https://github.com/sonic-pi-net/sonic-pi/commit/b346692b46233de05bccfd26d89bbb621b64cc9c

Which results in:

```ruby
Runtime Error: [buffer eval, line 27] - NameError Thread death!  uninitialized constant Ziffers::Grammar::Treetop 
```

This can be resolved by installing treetop and adding `require treetop` to zgrammar.rb

**Comment by amiika** [comment]
Thanks! I'll fix it once it ends up to the released version. I'll might also consider adding Treetop as an submodule to avoid installing treetop separately.

**Comment by amiika** [comment]
Will fix the issue once the next beta release is out.

**Comment by amiika** [comment]
Issue fixed in https://github.com/amiika/ziffers/tree/beta5
